# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OBDAtlas
email: atlas@carminestudios.com
description: > # this means to ignore newlines until "baseurl:"
  OBDAtlas, all you need to know about the OBD (On Board Diagnostics) port and
  protocol. We will soon supply an app for all major devices that will serve
  as a platform for you to talk/hack/read your vehicle data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://obdatlas.com" # the base hostname & protocol for your site
# twitter_username: OBDAtlas
github_username:  OBDAtlas

# Build settings
markdown: kramdown

# Custom collections (can be enumerated etc)
# {% for image in site.images %}
#      {% if image.extname == 'jpg' %}
#          <img src="{{ file.url }}" />
#      {% endif %}
# {% endfor %}
# collections:
# - pids
# - troublecodes
